name: Upload Python Package To PyPi

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Build package
        run: |
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
